CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS properties (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    address text,
    city text,
    state text,
    zip text,
    lat numeric,
    lng numeric,
    property_type text,
    listing_type text,
    status text,
    starting_price numeric,
    current_bid numeric,
    reserve_price numeric,
    lowest_rent_bid numeric,
    asking_price numeric,
    monthly_rate numeric,
    auction_end_date timestamptz,
    bedrooms int,
    bathrooms numeric,
    sq_ft int,
    lot_size int,
    year_built int,
    description text,
    images jsonb,
    virtual_tour_url text,
    open_house_dates jsonb,
    escrow_company_id uuid,
    mls_number text,
    is_multi_parcel boolean,
    parcels jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);